server {
   charset utf-8;
   client_max_body_size 512M;
   sendfile off;

   listen 80; ## listen for ipv4
   #listen [::]:80 default_server ipv6only=on; ## listen for ipv6

   server_name localhost;
   root        /www/web/web;
   index       index.html index.htm;

   #access_log  /www/wwwlog/label.kuaibiao.com.cn-access.log main;
   #error_log   /www/wwwlog/label.kuaibiao.com.cn-error.log;

   # cross domain
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers *;
    add_header Access-Control-Allow-Methods GET,POST,PUT,DELETE,OPTIONS;

   location / {
       # Redirect everything that isn't a real file to index.php
       try_files $uri $uri/ /index.html$is_args$args;
   }

   # uncomment to avoid processing of calls to non-existing static files by Yii
   #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
   #    try_files $uri =404;
   #}
   #error_page 404 /404.html;

   location ~ /\.(ht|svn|git) {
       deny all;
   }
}

server {
   charset utf-8;
   client_max_body_size 512M;
   sendfile off;

   listen 81; ## listen for ipv4
   #listen [::]:80 default_server ipv6only=on; ## listen for ipv6

   server_name localhost;
   root        /www/api/api/web;
   index       index.php;

   #access_log  /www/wwwlog/api.label.kuaibiao.com.cn-access.log main;
   #error_log   /www/wwwlog/api.label.kuaibiao.com.cn-error.log;

    # cross domain
    add_header Access-Control-Allow-Origin *;
    add_header Access-Control-Allow-Headers *;
    add_header Access-Control-Allow-Methods GET,POST,PUT,DELETE,OPTIONS;

   location / {
       # Redirect everything that isn't a real file to index.php
       # try_files $uri $uri/ /index.php$is_args$args;
       if (!-e $request_filename){
            rewrite ^(.*)$ /index.php?s=/$1 last;
            break;
       }
   }

   # uncomment to avoid processing of calls to non-existing static files by Yii
   #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
   #    try_files $uri =404;
   #}
   #error_page 404 /404.html;

   location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  /www/api/api/web/$fastcgi_script_name;
        include        fastcgi_params;
       #fastcgi_pass unix:/var/run/php5-fpm.sock;
       #try_files $uri =404;
   }

   location ~ /\.(ht|svn|git) {
       deny all;
   }
}

server {
   charset utf-8;
   client_max_body_size 512M;
   sendfile off;

   listen 82; ## listen for ipv4
   #listen [::]:80 default_server ipv6only=on; ## listen for ipv6

   server_name localhost;
   root        /www/api/publicfile/;
   index       index.html index.htm;

   #access_log  /www/wwwlog/public.label.kuaibiao.com.cn-access.log main;
   #error_log   /www/wwwlog/public.label.kuaibiao.com.cn-error.log;

   location / {
       # Redirect everything that isn't a real file to index.php
       try_files $uri $uri/ /index.php$is_args$args;
   }

   # uncomment to avoid processing of calls to non-existing static files by Yii
   #location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
   #    try_files $uri =404;
   #}
   #error_page 404 /404.html;

   location ~ /\.(ht|svn|git) {
       deny all;
   }
}

